Repository zwzone/ft_transcendence, pull requests merged in 2024-01, with the labels that each got.

#14 PR for issue #13
  .gitignore
  frontend/.prettierrc.cjs
  frontend/app.js
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.min.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.min.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.min.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.min.js.map
  frontend/index.html
Labels: enhancement

#15 PR for issue #11
  frontend/app.js
  frontend/router/router.js
Labels: enhancement

#16 PR for issue #9
  frontend/app.js
  frontend/index.html
  frontend/pages/NotfoundPage.js
Labels: enhancement

#21 PR for Frontend pages
  frontend/app.js
  frontend/components/Card.js
  frontend/components/Navbar.js
  frontend/index.html
  frontend/pages/GamePage.js
  frontend/pages/HomePage.js
  frontend/pages/LoginPage.js
  frontend/pages/ProfilePage.js
  frontend/pages/SettingPage.js
  frontend/pages/TournamentPage.js
  frontend/public/pong.ico
Labels: enhancement

#24 PR for issue #23
  frontend/index.html
  frontend/public/pong.ico
  frontend/public/pong.jpg
  frontend/public/pong_icon.png
  frontend/public/pong_logo.png
Labels: bug

#25 PR for issue #20
  .gitignore
  backend/authenticationapp/__init__.py
  backend/authenticationapp/admin.py
  backend/authenticationapp/apps.py
  backend/authenticationapp/migrations/0001_initial.py
  backend/authenticationapp/migrations/__init__.py
  backend/authenticationapp/models.py
  backend/authenticationapp/serializers.py
  backend/authenticationapp/tests.py
  backend/authenticationapp/urls.py
  backend/authenticationapp/views.py
  backend/core/__init__.py
  backend/core/asgi.py
  backend/core/settings.py
  backend/core/urls.py
  backend/core/wsgi.py
  backend/manage.py
  backend/requirements.txt
Labels: enhancement

#29 PR for issue #22
  frontend/components/Card.js
  frontend/components/Navbar.js
  frontend/index.html
  frontend/pages/GamePage.js
  frontend/pages/HomePage.js
  frontend/pages/LoginPage.js
  frontend/pages/NotfoundPage.js
  frontend/pages/ProfilePage.js
  frontend/pages/SettingPage.js
  frontend/pages/TournamentPage.js
  frontend/router/router.js
Labels: enhancement

#37 PR for issue #18
  backend/apiapp/__init__.py
  backend/apiapp/admin.py
  backend/apiapp/apps.py
  backend/apiapp/migrations/__init__.py
  backend/apiapp/models.py
  backend/apiapp/serializers.py
  backend/apiapp/tests.py
  backend/apiapp/urls.py
  backend/apiapp/views.py
  backend/core/settings.py
  backend/core/urls.py
  backend/requirements.txt
Labels: enhancement

#39 PR for issue #19
  backend/authenticationapp/migrations/0002_alter_player_first_name_alter_player_last_name.py
  backend/authenticationapp/migrations/0003_player_tournament_name_alter_player_display_name_and_more.py
  backend/authenticationapp/migrations/0004_googleaccesstokens_googlerawlogincredentials.py
  backend/authenticationapp/migrations/0005_remove_player_display_name_alter_player_username.py
  backend/authenticationapp/models.py
  backend/authenticationapp/serializers.py
  backend/authenticationapp/service.py
  backend/authenticationapp/urls.py
  backend/authenticationapp/views.py
  backend/core/settings.py
  backend/core/urls.py
  backend/requirements.txt
Labels: enhancement

#40 PR for issue #38
  .gitignore
  backend/apiapp/models.py
  backend/apiapp/views.py
  backend/authenticationapp/migrations/0001_initial.py
  backend/authenticationapp/migrations/0002_alter_player_first_name_alter_player_last_name.py
  backend/authenticationapp/migrations/0003_player_tournament_name_alter_player_display_name_and_more.py
  backend/authenticationapp/migrations/0004_googleaccesstokens_googlerawlogincredentials.py
  backend/authenticationapp/migrations/0005_remove_player_display_name_alter_player_username.py
  backend/authenticationapp/models.py
  backend/authenticationapp/serializers.py
  backend/authenticationapp/service.py
  backend/authenticationapp/views.py
  backend/core/settings.py
Labels: bug, enhancement

#41 PR for issue #27
  frontend/css/pong.css
  frontend/index.html
  frontend/pages/GamePage.js
  frontend/pong/pong.js
  frontend/public/background.jpg
Labels: enhancement

#43 PR for issue #42
  backend/apiapp/views.py
Labels: bug

#48 PR for issue #30
  frontend/app.js
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.css.map
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.min.css
  frontend/bootstrap-5.3.2-dist/css/bootstrap.rtl.min.css.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.min.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.esm.min.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.js.map
  frontend/bootstrap-5.3.2-dist/js/bootstrap.min.js
  frontend/bootstrap-5.3.2-dist/js/bootstrap.min.js.map
  frontend/components/Card.js
  frontend/components/FriendCard.js
  frontend/components/MatchCard.js
  frontend/components/Navbar.js
  frontend/components/PlayCard.js
  frontend/css/navbar.css
  frontend/css/pong.css
  frontend/css/style.css
  frontend/index.html
  frontend/router/router.js
Labels: enhancement

#47 ball collision with paddle bug fixed
  frontend/pages/GamePage.js
  frontend/pong/pong.js
Labels: enhancement

#50 PR for issue #30
  frontend/app.js
  frontend/components/LoginButton.js
  frontend/css/LoginPage.css
  frontend/index.html
  frontend/public/pong.svg
Labels: enhancement

#53 PR for issue #51
  frontend/.prettierrc.cjs
  frontend/components/PlayCard.js
  frontend/css/HomePage.css
  frontend/css/LoginPage.css
  frontend/css/Navbar.css
  frontend/css/root.css
  frontend/css/style.css
  frontend/index.html
  frontend/pong/pong.js
  frontend/public/leaf1.png
  frontend/public/leaf2.png
  frontend/public/leaf3.png
  frontend/public/leaf4.png
  frontend/public/leaf5.png
  frontend/public/pong.svg
Labels: enhancement

#60 PF for issue #5
  frontend/app.js
  frontend/components/TournamentMatchCard.js
  frontend/components/TournamentPlayerCard.js
  frontend/css/LoginPage.css
  frontend/css/Navbar.css
  frontend/css/TournamentPage.css
  frontend/css/style.css
  frontend/index.html
Labels: enhancement

#63 PR for issue #57
  services/player/api/models.py
  services/player/api/serializers.py
  services/player/api/urls.py
  services/player/api/views.py
Labels: bug, enhancement

#81 PR for issue #61
  services/authentication/api/middleware.py
  services/authentication/api/service.py
  services/authentication/api/settings.py
  services/authentication/api/urls.py
  services/authentication/api/views.py
  services/authentication/requirements.txt
Labels: enhancement

#83 PR for ( Deployment, Development, Automation ) Microservice.
  .gitignore
  Makefile
  docker-compose.dev.yaml
  docker-compose.yaml
  frontend/Dockerfile
  frontend/Dockerfile.dev
  frontend/conf/nginx.conf
  services/authentication/Dockerfile
  services/authentication/Dockerfile.dev
  services/authentication/tools/microservice-run.sh
  services/player/Dockerfile
  services/player/Dockerfile.dev
  services/player/tools/microservice-run.sh
Labels: enhancement

#82 PR for issue #62
  client/.prettierrc.cjs
  client/Dockerfile
  client/Dockerfile.dev
  client/app.js
  client/bootstrap-5.3.2-dist/css/bootstrap.min.css
  client/bootstrap-5.3.2-dist/css/bootstrap.min.css.map
  client/bootstrap-5.3.2-dist/js/bootstrap.min.js
  client/bootstrap-5.3.2-dist/js/bootstrap.min.js.map
  client/components/FriendCard.js
  client/components/LoginButton.js
  client/components/MatchCard.js
  client/components/Navbar.js
  client/components/PlayCard.js
  client/components/TournamentMatchCard.js
  client/components/TournamentPlayerCard.js
  client/conf/nginx.conf
  client/css/HomePage.css
  client/css/LoginPage.css
  client/css/Navbar.css
  client/css/ProfilePage.css
  client/css/TournamentPage.css
  client/css/pong.css
  client/css/root.css
  client/css/style.css
  client/index.html
  client/pages/GamePage.js
  client/pages/HomePage.js
  client/pages/LoginPage.js
  client/pages/NotfoundPage.js
  client/pages/ProfilePage.js
  client/pages/SettingPage.js
  client/pages/TournamentPage.js
  client/pong/pong.js
  client/public/background.jpg
  client/public/leaf1.png
  client/public/leaf2.png
  client/public/leaf3.png
  client/public/leaf4.png
  client/public/leaf5.png
  client/public/pong.jpg
  client/public/pong.svg
  client/public/pong_icon.png
  client/public/pong_logo.png
  client/router/router.js
  frontend/css/HomePage.css
  frontend/css/Navbar.css
  frontend/css/TournamentPage.css
  frontend/css/root.css
Labels: enhancement

#89 PR for issue #84
  client/css/Navbar.css
  client/css/ProfilePage.css
  client/css/SettingPage.css
  client/css/style.css
  client/index.html
Labels: enhancement

#90 PR for issue #59
  client/app.js
  client/components/Footer.js
  client/css/LoginPage.css
  client/css/root.css
  client/index.html
  client/pages/GamePage.js
  client/pages/HomePage.js
  client/pages/LoginPage.js
  client/pages/NotfoundPage.js
  client/pages/ProfilePage.js
  client/pages/SettingPage.js
  client/pages/TournamentPage.js
  client/public/pong.svg
Labels: enhancement

#91 PR for ( NGINX as Reverse-Proxy and HTTPS ). #85
  Makefile
  client/Dockerfile
  client/Dockerfile.dev
  client/conf/nginx.conf
  docker-compose.dev.yaml
  docker-compose.yaml
  services/authentication/Dockerfile
  services/authentication/Dockerfile.dev
  services/authentication/api/endpoints.py
  services/authentication/api/middleware.py
  services/authentication/api/settings.py
  services/authentication/api/urls.py
  services/authentication/api/views.py
  services/authentication/tools/microservice-run.sh
  services/player/Dockerfile
  services/player/Dockerfile.dev
  services/player/api/endpoints.py
  services/player/api/settings.py
  services/player/api/urls.py
  services/player/api/views.py
  services/player/tools/microservice-run.sh
Labels: enhancement

#92 PR for issue #88
  client/index.html
  services/authentication/api/endpoints.py
  services/authentication/api/settings.py
  services/authentication/api/views.py
  services/authentication/requirements.txt
  services/player/api/settings.py
  services/player/requirements.txt
Labels: enhancement

#94 PR for issue #93
  client/components/Navbar.js
  client/css/Navbar.css
  client/router/router.js
  client/utilities/fetching.js
  services/authentication/api/endpoints.py
Labels: enhancement

#99 PR for issue #98
  README.md
Labels: documentation

#95 PR for issue #77
  services/authentication/api/endpoints.py
  services/authentication/api/guard.py
  services/authentication/api/middleware.py
  services/authentication/api/service.py
  services/authentication/api/views.py
  services/player/api/models.py
  services/player/api/views.py
Labels: enhancement

#104 PR for issue #100
  client/components/Navbar.js
  client/css/LoginPage.css
  client/css/Navbar.css
  client/css/pong.css
  client/index.html
  client/pages/ProfilePage.js
  client/pages/SettingPage.js
  client/public/stadium.jpeg
  client/router/router.js
  services/authentication/api/endpoints.py
  services/authentication/api/middleware.py
  services/authentication/api/settings.py
  services/authentication/api/urls.py
  services/authentication/api/views.py
  services/authentication/requirements.txt
  services/player/api/settings.py
  services/player/api/urls.py
  services/player/api/views.py
  services/player/requirements.txt
Labels: bug

#106 FEAT: Daphne server for backend microservices
  Makefile
  client/Dockerfile
  client/Dockerfile.dev
  client/conf/nginx.conf
  services/authentication/Dockerfile
  services/authentication/Dockerfile.dev
  services/authentication/requirements.txt
  services/authentication/tools/microservice-run.sh
  services/player/Dockerfile
  services/player/Dockerfile.dev
  services/player/requirements.txt
  services/player/tools/microservice-run.sh
Labels: enhancement

#107 PR for issue #96
  services/player/api/endpoints.py
  services/player/api/models.py
  services/player/api/urls.py
  services/player/api/views.py
Labels: enhancement

#111 PR for issue #54
  services/matchmaking/api/__init__.py
  services/matchmaking/api/asgi.py
  services/matchmaking/api/consumers.py
  services/matchmaking/api/routing.py
  services/matchmaking/api/settings.py
  services/matchmaking/api/urls.py
  services/matchmaking/api/wsgi.py
  services/matchmaking/manage.py
Labels: enhancement

#109 PR for issue #105
  services/authentication/api/service.py
  services/authentication/api/views.py
  services/player/api/decorators.py
  services/player/api/endpoints.py
  services/player/api/views.py
Labels: bug, enhancement
