Repository zwzone/ft_transcendence, pull requests merged in 2024-02, with the labels that each got.

#114 FEAT: Add Avatar POST
  .gitignore
  services/authentication/api/endpoints.py
  services/authentication/api/settings.py
  services/player/api/decorators.py
  services/player/api/endpoints.py
  services/player/api/settings.py
  services/player/api/urls.py
  services/player/api/views.py
Labels: enhancement

#115 PR for issue #110
  client/css/SettingPage.css
  client/index.html
  client/pages/ProfilePage.js
  client/pages/SettingPage.js
  client/public/image-edit.svg
  client/utilities/fetching.js
  services/authentication/api/urls.py
  services/player/api/models.py
  services/player/api/urls.py
  services/player/api/views.py
Labels: enhancement

#120 FEAT: make the hostname our system dynamic
  client/app.js
  client/css/ProfilePage.css
  client/index.html
  client/pages/ProfilePage.js
  client/pages/SettingPage.js
  client/pong/pong.js
  client/router/router.js
  services/authentication/api/settings.py
  services/authentication/api/views.py
  services/player/api/settings.py
Labels: enhancement

#122 FEAT: websocket secure in matchmaking and pong
  services/matchmaking/api/asgi.py
  services/matchmaking/api/settings.py
  services/matchmaking/requirements.txt
  services/pong/api/asgi.py
  services/pong/api/settings.py
  services/pong/requirements.txt
Labels: enhancement

#124 FEAT: Add friendship system.
  services/player/api/endpoints.py
  services/player/api/views.py
Labels: enhancement

#126 FIX: add authority to JWT payload
  services/authentication/api/service.py
  services/authentication/api/views.py
  services/player/api/views.py
Labels: bug

#128 FIX: Added JWT required decorator
  services/authentication/api/service.py
  services/authentication/api/views.py
  services/player/api/views.py
Labels: bug, enhancement

#141 FIX: fix creat player
  services/authentication/api/service.py
  services/authentication/api/views.py
  services/player/api/views.py
Labels: enhancement

#136 PR for issue #135
  client/pages/SettingPage.js
  services/player/api/views.py
Labels: bug

#145 FEAT: optimization and styling pong game
  client/utilities/pong.js
  services/pong/api/consumers.py
  services/pong/api/settings.py
Labels: enhancement

#146 FEAT: adding middlware to matchmaking and pong apps
  client/utilities/pong.js
  services/matchmaking/api/asgi.py
  services/matchmaking/api/consumers.py
  services/matchmaking/api/middleware.py
  services/matchmaking/api/settings.py
  services/matchmaking/requirements.txt
  services/pong/api/asgi.py
  services/pong/api/middleware.py
  services/pong/api/settings.py
  services/pong/requirements.txt
Labels: enhancement

#148 FEAT: postgres with Django
  services/authentication/api/settings.py
  services/matchmaking/api/settings.py
  services/player/api/settings.py
  services/pong/api/settings.py
Labels: enhancement

#147 Adding the Postgres and pgadmin containers
  docker-compose.dev.yaml
  docker-compose.yaml
  services/postgres/Dockerfile
  services/postgres/conf/postgresql.conf
  services/postgres/tools/microservice-run.sh
Labels: enhancement

#150 FIX: fix the link between backend and postgres database
  services/authentication/api/settings.py
  services/authentication/requirements.txt
  services/authentication/tools/microservice-run.sh
  services/matchmaking/api/models.py
  services/matchmaking/api/settings.py
  services/matchmaking/requirements.txt
  services/player/api/settings.py
  services/player/api/views.py
  services/player/requirements.txt
  services/player/tools/microservice-run.sh
  services/pong/api/models.py
  services/pong/api/settings.py
  services/pong/requirements.txt
  services/pong/tools/microservice-run.sh
Labels: bug

#152 FEAT: link buttons of playing with backend
  client/components/PlayCard.js
  client/css/GamePage.css
  client/css/HomePage.css
  client/css/style.css
  client/index.html
  client/pages/GamePage.js
  client/utilities/pongCoop.js
  client/utilities/pongFour.js
  client/utilities/pongTwo.js
Labels: enhancement

#157 FEAT: add pong coop mode
  client/index.html
  client/utilities/pongCoop.js
  client/utilities/pongTwo.js
Labels: enhancement

#161 FEAT: creating tournament
  services/tournament/api/__init__.py
  services/tournament/api/asgi.py
  services/tournament/api/decorators.py
  services/tournament/api/endpoints.py
  services/tournament/api/models.py
  services/tournament/api/serializers.py
  services/tournament/api/settings.py
  services/tournament/api/urls.py
  services/tournament/api/views.py
  services/tournament/api/wsgi.py
  services/tournament/manage.py
  services/tournament/requirements.txt
Labels: enhancement

#159 Fixing friendship system
  services/player/api/serializers.py
  services/player/api/views.py
Labels: bug, enhancement

#163 FEAT: Tournament container and db healthcheck
  client/conf/nginx.conf
  docker-compose.dev.yaml
  docker-compose.yaml
  services/tournament/Dockerfile
  services/tournament/Dockerfile.dev
  services/tournament/private/ssl/certs/ft_transcendence.crt
  services/tournament/private/ssl/private/ft_transcendence.key
  services/tournament/tools/microservice-run.sh
Labels: bug, enhancement
